services:
  mage:
    # Service for Data Transformation using shared MS SQL Server
    # Container will not spin up unless `docker compose --profile t up` is used
    build:
      context: devops/mage
      dockerfile: Dockerfile
      args:
        PIPENVFILE: requirements.txt
    image: ${IMAGE_REGISTRY}/${IMAGE_REPO}/mage:latest
    env_file:
      - .env
    volumes:
      ## Mount docker host directory to the container (i.e. current directory)
      - .:/home/src
    ports:
      - "127.0.0.1:6789-6799:6789" # mage
      - "127.0.0.1:8082-8090:8080" # dbt docs
    networks:
      - magic-network
    deploy:
      resources:
        limits:
          memory: 5000M

networks:
  magic-network:
    driver: bridge
